# CONFIGURATION FILE - https://docs.netlify.com/configure-builds/file-based-configuration/#sample-netlify-toml-file
# ENVIRONMENT VARIABLES - https://docs.netlify.com/environment-variables/get-started/#create-variables-with-a-netlify-configuration-file
# SET NODE VERSION - https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

# [build.processing]
#   skip_processing = true

# [build.processing.js]
#   bundle = false
#   minify = false

[build.environment]
  NODE_VERSION = "18.14.0"

[functions]
  directory = "build/lambda/" #DEFAULT: "netlify/functions/"
  external_node_modules = ["knex","pg"] #DEFAULT: []

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  # SPLATS = https://docs.netlify.com/routing/redirects/redirect-options/#splats

[dev]
  publish = "dist"
  port = 8000 #DEFAULT: 8888

[context.dev.environment]
  hostEnvironment = "lambda"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"